#######################################################
# 
# FO.py
# Python implementation of the Class FO
# Generated by Enterprise Architect
# Created on:      10-nov.-2018 11:27:46 p. m.
# Original author: Habib Navarro Acosta
# 
#######################################################

class FO():
    def __init__(self, coef, maximizar = True):
        self.max = maximizar                                   # Maximizar o minimizar.
        self.coef = coef                                       # Coeficientes de la función objetivo.
        if not maximizar:
            for i in range(len(self.coef)):
                self.coef[i] *= -1                             # Método de minimizar